### ISSUE TITLE
Invalid key hash.

### ISSUE THREAD

**Issue by kofii12345** [fbsamples/android-friend-smash#4]
I get "Invalid key hash. <myhash> does not match any stored key hashes. (...)" error while trying to log in on main activity.

**Comment by mlayton20** [comment]
Same.

**Comment by skoggkatt** [comment]
@mlayton20 - that would indeed fix the issue, thanks for posting it here. Alternatively you should be able to enter the key hash on https://developers.facebook.com/settings/developer/sample-app/ as is described in the [Android Getting Started](https://developers.facebook.com/docs/android/getting-started) doc linked from this project's README. This way you don't need to create a new app and change strings.xml
