### ISSUE TITLE
Game request does not showing up on recipient profile?

### ISSUE THREAD

**Issue by hummatli** [fbsamples/android-friend-smash#5]
I have configured my own Friend Smash . It was sending request initially (About 6-8 month ago). But now Friend Smash does not send request. I press challenge, then press send (both invite and request mode), select friend , press send. Log shows success. But there is nothing on recipient profile about request.

**Comment by DomenicoDeFelice** [comment]
Hi hummatli,

Can you confirm this was the same issue reported at https://developers.facebook.com/bugs/1170355363046592/?

Thanks,
Dom

**Comment by hummatli** [comment]
Hi @DomenicoDeFelice .

Yes this was the same issue reported on https://developers.facebook.com/bugs/1170355363046592/.

I'm confirming to close issue #5

Thanks, for helping.

**Comment by edgarjcfn** [comment]
Thanks for clearing this @DomenicoDeFelice. Closing the issue.
